### ISSUE TITLE
Add CodeChef solutions

### ISSUE THREAD

**Issue by MilindGupta-Creator** [MilindGupta-Creator/Competitive-Coding-Section#1]
Create a separate branch/folder and further a branch/folder labelling it as Beginner level or Easy section.
Further solutions must be in C or C++ language only.
explaining your approach in a clear way, no plagiarism/copying should be there.

**Comment by Srijan7777** [comment]
Can i contribute to this?

**Comment by MilindGupta-Creator** [comment]
> Can I contribute to this?

yes but mention here what you are going to do and then proceed

**Comment by Srijan7777** [comment]
I'll add some codechef beginner and easy ques soln.
so I have to make a beginner and an easy folder, right?

**Comment by MilindGupta-Creator** [comment]
> I'll add some codechef beginner and easy ques soln.
> so I have to make a beginner and an easy folder, right?

yes

**Comment by Adarsh08X** [comment]
Can i also work on this repo?

**Comment by MilindGupta-Creator** [comment]
yes it's open for up to 48 hours.

**Comment by rising-entropy** [comment]
@MilindGupta-Creator What should be the name of the folder in which we store folders with difficulty levels?

**Comment by MilindGupta-Creator** [comment]
Folder name is simple like codechef solution then easy medium section whichever u like
