### ISSUE TITLE
Add your preffered Algorithma

### ISSUE THREAD

**Issue by MilindGupta-Creator** [MilindGupta-Creator/Competitive-Coding-Section#2]
**Create a separate branch/folder and further a branch/folder labelling it as Sorting , Greedy, Backtracking, etc.
Further solutions must be in C or C++ language only.
explaining your approach in a clear way, no plagiarism/copying should be there.**

**Comment by Adarsh08X** [comment]
Hey i would like to add some easy array algorithms like kadane's , two-pointer etc.

**Comment by MilindGupta-Creator** [comment]
Yes you can go with it

**Comment by Zeph-T** [comment]
I would like to add Fractional Knapsack Greedy Algorithm,Can I do it?

**Comment by MilindGupta-Creator** [comment]
> I would like to add Fractional Knapsack Greedy Algorithm,Can I do it?

sure add it create a greedy algorithm folder and then your fractional knapsack keeping in mind how the issue is mentioned like telling your approach too with code

**Comment by Zeph-T** [comment]
Sorry i implemented it in python, i will do Feul Refilling in C++

**Comment by kshitij5** [comment]
can I still contribute?
I would like to add the TSP problem!

**Comment by MilindGupta-Creator** [comment]
Yes you can do just check the repository how everyone has done

**Comment by yashgupta18** [comment]
can I add some DP programs in c++??

**Comment by MilindGupta-Creator** [comment]
Yes please add with a bit explanation.

**Comment by yashgupta18** [comment]
sure. thnx
