### ISSUE TITLE
Update the Readme file which should describes this repository

### ISSUE THREAD

**Issue by MilindGupta-Creator** [MilindGupta-Creator/Competitive-Coding-Section#3]

**Comment by 06rakshitha** [comment]
Hello!
Can I contribute to this file?

**Comment by 06rakshitha** [comment]
Hey can I contribute to this file?

**Comment by MilindGupta-Creator** [comment]
Yes sure, but can you mention what changed you want to made?

**Comment by MilindGupta-Creator** [comment]
> Hey can I contribute to this file?

Can you tell what changes you want to make

**Comment by sarsiz** [comment]
There was a spelling mistake in README, corrected that.

**Comment by chem-p** [comment]
Added Proper markdown, and restructured the lines. Now it looks more elegant.

**Comment by sovetw** [comment]
I made some edits to the readme to make it look more organized. Please review the pull request.
