### ISSUE TITLE
Adding binary search problems

### ISSUE THREAD

**Issue by Devolious** [MilindGupta-Creator/Competitive-Coding-Section#70]
Would like to add a few good level binary search problem. Please assign me the task.

**Comment by Naprila** [comment]
I would also like to add some good questions on Heap, Stack and Dp.

**Comment by MilindGupta-Creator** [comment]
Kindly make a folder like Binary Search and similarly heap stack don't make for dp as it's already in the main branch

**Comment by Naprila** [comment]
Ok got it.

**Comment by Devolious** [comment]
@MilindGupta-Creator I have added aggressive cows approach and solution in CPP please merge my pull request
