### ISSUE TITLE
Adding more problems to greedy section.

### ISSUE THREAD

**Issue by aditi10701** [MilindGupta-Creator/Competitive-Coding-Section#80]
Adding problems like 
N meetings in a room
Minimum Number of coins.
Job sequencing problem
Minimum number of platforms required.
and more problems can be added to this.
Kindly assign me the same.
#56

**Comment by MilindGupta-Creator** [comment]
Hey Aditi kindly all those in Algorithms folder
I will label you as Hacktoberfest accepted there itself
