### ISSUE TITLE
Add GFG solutions 

### ISSUE THREAD

**Issue by MilindGupta-Creator** [MilindGupta-Creator/Competitive-Coding-Section#9]
Create a separate branch/folder and further a branch/folder labelling it as Beginner level or Easy section.
Further solutions must be in C or C++ language only.
explaining your approach in a clear way, no plagiarism/copying should be there.

**Comment by hritik5102** [comment]
Hello @MilindGupta-Creator  , I would like to work on this issue

Following thing, I would like to add in this repo 
- [x] **_Area_of_triangle using C with documentation_** 

Thank you

**Comment by MilindGupta-Creator** [comment]
Yes sure make a folder and place it

**Comment by coding-sourabh** [comment]
I will add this problem : Find the only repeated element in the array.

**Comment by hritik5102** [comment]
@MilindGupta-Creator Check out PR #28
