### ISSUE TITLE
Reverse a Linked List in Kth group

### ISSUE THREAD

**Issue by heyhimansh** [MilindGupta-Creator/Competitive-Coding-Section#90]
Hey @MilindGupta-Creator  , I would like to contribute on this and also i have good grip on c++ language.
please assign it to me as my Hacktoberfest2022 PR

**Comment by TanuJain2002** [comment]
Hello @MilindGupta-Creator ,Plz assign me this  I can code it in C++ and Java too

**Comment by MilindGupta-Creator** [comment]
Please continue adding into the right folder and i will mark you as hacktober accepted
